import type { ArchitectureMap } from "./types.ts";
import { normalizeArchitectureMap } from "./validation.ts";

const SUBSYSTEMS = [
  {
    id: "document-model",
    title: "Document model",
    owner: "@lilac/document-model",
    status: "implemented",
    boundary: "Typed Lilac document graph, nodes, and identities. Sole structural authority alongside history.",
    dependsOn: [],
  },
  {
    id: "history",
    title: "History",
    owner: "@lilac/history",
    status: "implemented",
    boundary: "Reversible history transactions. Sole canonical document mutation authority alongside document-model.",
    dependsOn: ["document-model"],
  },
  {
    id: "canvas-viewport",
    title: "Canvas and viewport",
    owner: "@lilac/canvas",
    status: "stub",
    boundary: "Pan, zoom and viewport transforms over the rendered document, with hit testing through the renderer's node identity (PC3). Reads document-model; never mutates it directly.",
    dependsOn: ["document-model", "renderer"],
  },
  {
    id: "selection-transform",
    title: "Selection, transform, and snapping",
    owner: "@lilac/canvas",
    status: "stub",
    boundary: "Selection sets and move, resize, nudge, reorder, insert and delete commands that produce history operations, with drag previews committed once on release (PC3). Rotation, grouping, clipping and snapping guides are planned.",
    dependsOn: ["canvas-viewport", "document-model"],
  },
  {
    id: "layout-css",
    title: "Layout and CSS semantics",
    owner: "@lilac/layout",
    status: "planned",
    boundary: "CSS-oriented layout semantics, constraints during parent resize, and flexbox spacing rules.",
    dependsOn: ["document-model", "tokens-themes"],
  },
  {
    id: "text",
    title: "Text",
    owner: "@lilac/text",
    status: "planned",
    boundary: "Text runs, platform type ramps, and text editing semantics over document nodes.",
    dependsOn: ["document-model"],
  },
  {
    id: "vector",
    title: "Vector",
    owner: "@lilac/vector",
    status: "planned",
    boundary: "Vector paths, shapes, booleans, and SVG export semantics over document nodes.",
    dependsOn: ["document-model"],
  },
  {
    id: "images-media",
    title: "Images and media",
    owner: "@lilac/media",
    status: "planned",
    boundary: "Image and media nodes, asset references, and export semantics. Intake provenance comes from import-export.",
    dependsOn: ["document-model", "import-export"],
  },
  {
    id: "components",
    title: "Components, variants, and slots",
    owner: "@lilac/design-components",
    status: "stub",
    boundary: "Code-linked component contracts with typed props, slots, states, and variants bound to code-ir symbols, verified-patch variants, drift detection, and source-linked previews (P05 D2 vertical slice). Canvas instances, overrides, and responsive variants are planned. Never flattened screenshots.",
    dependsOn: ["document-model", "code-ir", "tokens-themes"],
  },
  {
    id: "tokens-themes",
    title: "Tokens and themes",
    owner: "@lilac/tokens",
    status: "planned",
    boundary: "CSS-variable-oriented design tokens, themes, and modes consumed by layout, components, and the renderer.",
    dependsOn: ["document-model"],
  },
  {
    id: "renderer",
    title: "Renderer",
    owner: "@lilac/renderer",
    status: "stub",
    boundary: "Read-only rendering of document state as web semantics in a script-free sandboxed frame: allowlisted tags, attributes, URLs and styles under the frozen web-semantic props convention (tag, text, attributes, style), a stable data-lilac-id node to DOM identity, and incremental patches from history affectedNodeIds (PC2). Layout comes from the browser's CSS engine; tokens, text shaping, vector editing and media remain their own planned subsystems.",
    dependsOn: ["document-model"],
  },
  {
    id: "persistence",
    title: "Persistence",
    owner: "@lilac/persistence",
    status: "stub",
    boundary: "Local project persistence for documents: content-addressed objects, a hash-chained append-only journal of history transactions, atomic writes, crash recovery, single-writer locking, and manifest migration (P05 D6a). Agent-state persistence is planned. Document state is only produced by replaying history transactions.",
    dependsOn: ["document-model", "history"],
  },
  {
    id: "collaboration",
    title: "Collaboration and presence",
    owner: "@lilac/collaboration",
    status: "implemented",
    boundary: "Local-first collaboration, presence, comments, activity, and agent attribution through history transactions.",
    dependsOn: ["history", "agent-runtime"],
  },
  {
    id: "import-export",
    title: "Import and export",
    owner: "@lilac/import-stack",
    status: "implemented",
    boundary: "Provenance-preserving untrusted intake producing proposals; canonical mutation only through history. Export side planned.",
    dependsOn: ["document-model", "history", "network-policy"],
  },
  {
    id: "code-ir",
    title: "Code intermediate representation",
    owner: "@lilac/code-ir",
    status: "stub",
    boundary: "Stable Lilac code/design IR with rendered node to source symbol provenance. Bounded JSX/TSX, CSS, and Tailwind adapters with range-anchored source patches are delivered (P05 D1 vertical slice); full-language parsing and further languages are planned.",
    dependsOn: ["document-model"],
  },
  {
    id: "round-trip-sync",
    title: "Round-trip synchronization",
    owner: "@lilac/code-ir",
    status: "stub",
    boundary: "Conflict detection, hunk-based three-way reconciliation, and golden code/design round-trip fixpoints are delivered (P05 D1 vertical slice); live canvas-to-source synchronization is planned. Never silently overwrites human code.",
    dependsOn: ["code-ir", "history"],
  },
  {
    id: "agent-runtime",
    title: "Agent runtime",
    owner: "@lilac/agent-runtime",
    status: "implemented",
    boundary: "Durable replayable agent sessions, operation envelopes, and document transaction binding.",
    dependsOn: ["history"],
  },
  {
    id: "agent-events",
    title: "Agent event protocol",
    owner: "@lilac/agent-events",
    status: "implemented",
    boundary: "Typed event, replay, sequencing, correlation, and handler isolation protocol for agent activity.",
    dependsOn: ["agent-runtime"],
  },
  {
    id: "agent-supervisor",
    title: "Agent supervisor",
    owner: "@lilac/agent-supervisor",
    status: "implemented",
    boundary: "Local process and worktree supervision, leases, restart reconciliation, and one-owner mutation authority.",
    dependsOn: ["agent-runtime", "agent-events"],
  },
  {
    id: "mcp-surface",
    title: "Agent runtime MCP surface",
    owner: "@lilac/mcp-protocol",
    status: "stub",
    boundary: "MCP contract validation (client, tool, server-config, and Paper tool-set compatibility) and tool-call authorization through the collaboration access oracle exist. The capability-scoped local MCP endpoint for project discovery, inspection, queries, and transaction-aware edits is planned (#82) and must authorize every call.",
    dependsOn: ["agent-runtime", "document-model", "history", "collaboration"],
  },
  {
    id: "design-assurance",
    title: "Design assurance",
    owner: "@lilac/design-assurance",
    status: "implemented",
    boundary: "Deterministic local design checks with rule packs, including an accessibility audit of generated and imported output; findings outrank probabilistic recommendations. Browser-scan targets are classified by network-policy.",
    dependsOn: ["document-model", "network-policy"],
  },
  {
    id: "decision-router",
    title: "Decision router",
    owner: "@lilac/decision-router",
    status: "implemented",
    boundary: "Provider-neutral decisions with confidence, abstention, and review routing; never overrides deterministic violations.",
    dependsOn: ["design-assurance"],
  },
  {
    id: "decision-assurance",
    title: "Decision assurance",
    owner: "@lilac/decision-assurance",
    status: "stub",
    boundary: "Assures sets of agent-generated alternatives: deterministic rule-pack, accessibility, layout, and design-system (type scale, spacing grid) checks decide eligibility first; optional decision-router ranking orders eligible candidates; explicit abstention with preserved rationale and evidence. Color-contrast and token-conformance checks are planned until snapshots carry color and token data. Records and recommends only; never mutates documents or applies candidates.",
    dependsOn: ["decision-router", "design-method"],
  },
  {
    id: "delivery-governance",
    title: "Delivery governance",
    owner: "@lilac/delivery-governance",
    status: "implemented",
    boundary: "Exact-head qualification records, invalidation on mutation, repair ancestry, and ask-user gates for source delivery.",
    dependsOn: ["agent-supervisor"],
  },
  {
    id: "design-method",
    title: "Design method and resources",
    owner: "@lilac/design-method",
    status: "implemented",
    boundary: "Explainable method rule packs, deterministic review candidates, checklists, and the licensed resource registry.",
    dependsOn: ["design-assurance"],
  },
  {
    id: "agent-workspace",
    title: "Multi-agent workspace",
    owner: "@lilac/agent-workspace",
    status: "implemented",
    boundary: "Program role registry with capability scopes, role assignment, out-of-scope rejection, and an append-only attributed action ledger with cancellation and reversal marking. Records and gates agent work only; never mutates documents, executes tools, or reverses history.",
    dependsOn: ["agent-runtime", "agent-events", "agent-supervisor", "collaboration"],
  },
  {
    id: "visual-git",
    title: "Visual Git",
    owner: "@lilac/visual-git",
    status: "implemented",
    boundary: "Design snapshots bound to source commits, structural diffs, anchored review comments, design/code links, three-way conflict reports, and exact-head acceptance gates. Records, compares, and gates only; never executes git, mutates documents, or produces merged snapshots.",
    dependsOn: ["document-model", "code-ir"],
  },
  {
    id: "architecture-ownership",
    title: "Architecture ownership map",
    owner: "@lilac/architecture",
    status: "implemented",
    boundary: "Machine-checked subsystem ownership catalog and its validation. Declarative only; owns no runtime behavior.",
    dependsOn: [],
  },
  {
    id: "network-policy",
    title: "Network capability policy and providers",
    owner: "@lilac/network-policy",
    status: "implemented",
    boundary: "Default-deny network capability policy (offline, local-only, allowlist grants) with two-phase URL and resolved-address decisions, the single owner of address classification (consumed by import-stack, intake, and design-assurance browser scans), a bring-your-own provider registry holding credential references only, and offline readiness reporting. Decides only; never opens connections, resolves names, or stores credential values.",
    dependsOn: [],
  },
  {
    id: "intake",
    title: "Website and app intake product layer",
    owner: "@lilac/intake",
    status: "implemented",
    boundary: "Review-before-commit summaries of import proposals, web semantics derived only from markup (OBSERVED evidence), commit of reviewed imports into persisted projects through the import-stack history transaction, network imports gated by import.fetch policy decisions, and an advisory accessibility summary of each proposal from design-assurance. Composes import-stack, network-policy, persistence, and design-assurance; creates no second document authority.",
    dependsOn: ["import-export", "network-policy", "persistence", "history", "design-assurance"],
  },
  {
    id: "desktop-bridge",
    title: "Desktop bridge",
    owner: "@lilac/desktop",
    status: "planned",
    boundary: "Desktop builds, local MCP endpoint hosting, and OS integration where applicable. Optional per target.",
    dependsOn: ["mcp-surface", "persistence"],
  },
  {
    id: "sandbox-security",
    title: "Sandbox and security",
    owner: "@lilac/import-stack",
    status: "stub",
    boundary: "Import sanitization, authority limits, and bounded capture are implemented. General execution sandboxing is planned.",
    dependsOn: ["document-model", "agent-supervisor"],
  },
  {
    id: "plugin-surface",
    title: "Plugin surface",
    owner: "@lilac/plugins",
    status: "planned",
    boundary: "Capability-scoped plugin and connector surface for optional providers. No implicit authority.",
    dependsOn: ["mcp-surface", "sandbox-security"],
  },
] as const;

export const LILAC_ARCHITECTURE_MAP: ArchitectureMap = normalizeArchitectureMap({
  schemaVersion: 1,
  subsystems: [...SUBSYSTEMS],
});
