import type { ArchitectureMap } from "./types.ts";
import { normalizeArchitectureMap } from "./validation.ts";

const SUBSYSTEMS = [
  {
    id: "document-model",
    title: "Document model",
    owner: "@ninerr/document-model",
    status: "implemented",
    boundary: "Typed Ninerr document graph, nodes, and identities. Sole structural authority alongside history.",
    dependsOn: [],
  },
  {
    id: "history",
    title: "History",
    owner: "@ninerr/history",
    status: "implemented",
    boundary: "Reversible history transactions. Sole canonical document mutation authority alongside document-model.",
    dependsOn: ["document-model"],
  },
  {
    id: "canvas-viewport",
    title: "Canvas and viewport",
    owner: "@ninerr/canvas",
    status: "implemented",
    boundary: "Pan, zoom and viewport transforms over the rendered document, with hit testing through the renderer's node identity (PC3). Reads document-model; never mutates it directly.",
    dependsOn: ["document-model", "renderer"],
  },
  {
    id: "selection-transform",
    title: "Selection, transform, and snapping",
    owner: "@ninerr/canvas",
    status: "stub",
    boundary: "Selection sets and move, resize, nudge, reorder, insert and delete commands that produce history operations, with drag previews committed once on release (PC3). Rotation, grouping, clipping and snapping guides are planned.",
    dependsOn: ["canvas-viewport", "document-model"],
  },
  {
    id: "layout-css",
    title: "Layout and CSS semantics",
    owner: "@ninerr/layout",
    status: "planned",
    boundary: "CSS-oriented layout semantics, constraints during parent resize, and flexbox spacing rules.",
    dependsOn: ["document-model", "tokens-themes"],
  },
  {
    id: "text",
    title: "Text",
    owner: "@ninerr/text",
    status: "planned",
    boundary: "Text runs, platform type ramps, and text editing semantics over document nodes.",
    dependsOn: ["document-model"],
  },
  {
    id: "vector",
    title: "Vector",
    owner: "@ninerr/vector",
    status: "planned",
    boundary: "Vector paths, shapes, booleans, and SVG export semantics over document nodes.",
    dependsOn: ["document-model"],
  },
  {
    id: "images-media",
    title: "Images and media",
    owner: "@ninerr/media",
    status: "planned",
    boundary: "Image and media nodes, asset references, and export semantics. Intake provenance comes from import-export.",
    dependsOn: ["document-model", "import-export"],
  },
  {
    id: "components",
    title: "Components, variants, and slots",
    owner: "@ninerr/design-components",
    status: "stub",
    boundary: "Code-linked component contracts with typed props, slots, states, and variants bound to code-ir symbols, verified-patch variants, drift detection, and source-linked previews (P05 D2 vertical slice). Canvas instances, overrides, and responsive variants are planned. Never flattened screenshots.",
    dependsOn: ["document-model", "code-ir", "tokens-themes"],
  },
  {
    id: "tokens-themes",
    title: "Tokens and themes",
    owner: "@ninerr/tokens",
    status: "planned",
    boundary: "CSS-variable-oriented design tokens, themes, and modes consumed by layout, components, and the renderer.",
    dependsOn: ["document-model"],
  },
  {
    id: "renderer",
    title: "Renderer",
    owner: "@ninerr/renderer",
    status: "implemented",
    boundary: "Read-only rendering of document state as web semantics in a script-free sandboxed frame: allowlisted tags, attributes, URLs and styles under the frozen web-semantic props convention (tag, text, attributes, style), a stable data-ninerr-id node to DOM identity, and incremental patches from history affectedNodeIds (PC2). Layout comes from the browser's CSS engine; tokens, text shaping, vector editing and media remain their own planned subsystems.",
    dependsOn: ["document-model"],
  },
  {
    id: "persistence",
    title: "Persistence",
    owner: "@ninerr/persistence",
    status: "stub",
    boundary: "Local project persistence for documents: content-addressed objects, a hash-chained append-only journal of history transactions, atomic writes, crash recovery, single-writer locking, and manifest migration (P05 D6a). Agent-state persistence is planned. Document state is only produced by replaying history transactions.",
    dependsOn: ["document-model", "history"],
  },
  {
    id: "collaboration",
    title: "Collaboration and presence",
    owner: "@ninerr/collaboration",
    status: "implemented",
    boundary: "Local-first collaboration, presence, comments, activity, and agent attribution through history transactions.",
    dependsOn: ["history", "agent-runtime"],
  },
  {
    id: "import-export",
    title: "Import and export",
    owner: "@ninerr/import-stack",
    status: "stub",
    boundary: "Provenance-preserving untrusted intake producing proposals; canonical mutation only through history. Export to code is delivered: a layer as a JSX component, through code-ir and the studio host's code export (PC6). Export to images, PDF and other file formats is planned.",
    dependsOn: ["document-model", "history", "network-policy"],
  },
  {
    id: "code-ir",
    title: "Code intermediate representation",
    owner: "@ninerr/code-ir",
    status: "stub",
    boundary: "Stable Ninerr code/design IR with rendered node to source symbol provenance. Bounded JSX/TSX, CSS, and Tailwind adapters with range-anchored source patches are delivered (P05 D1 vertical slice); full-language parsing and further languages are planned.",
    dependsOn: ["document-model"],
  },
  {
    id: "round-trip-sync",
    title: "Round-trip synchronization",
    owner: "@ninerr/code-ir",
    status: "stub",
    boundary: "Conflict detection, hunk-based three-way reconciliation, and golden code/design round-trip fixpoints are delivered (P05 D1 vertical slice). From a connected codebase folder (PC11), components come into the design bound to their source, and edits to their text and literal props are written back as a previewed, three-way, range-anchored patch; structural edits and live synchronization are planned. Never silently overwrites human code.",
    dependsOn: ["code-ir", "history"],
  },
  {
    id: "agent-runtime",
    title: "Agent runtime",
    owner: "@ninerr/agent-runtime",
    status: "implemented",
    boundary: "Durable replayable agent sessions, operation envelopes, and document transaction binding.",
    dependsOn: ["history"],
  },
  {
    id: "agent-events",
    title: "Agent event protocol",
    owner: "@ninerr/agent-events",
    status: "implemented",
    boundary: "Typed event, replay, sequencing, correlation, and handler isolation protocol for agent activity.",
    dependsOn: ["agent-runtime"],
  },
  {
    id: "agent-supervisor",
    title: "Agent supervisor",
    owner: "@ninerr/agent-supervisor",
    status: "implemented",
    boundary: "Local process and worktree supervision, leases, restart reconciliation, and one-owner mutation authority.",
    dependsOn: ["agent-runtime", "agent-events"],
  },
  {
    id: "mcp-surface",
    title: "Agent runtime MCP surface",
    owner: "@ninerr/mcp-protocol",
    status: "implemented",
    boundary: "MCP contract validation (client, tool, server-config, and the server's tools against Ninerr's tool catalog) and tool-call authorization through the collaboration access oracle. The local MCP endpoint runs in the studio host (PC5, #82): Streamable HTTP on loopback plus a stdio relay, agents connected by the person with their own credentials, every call through requireMCPToolCall, agent edits as attributed history transactions, and the person's confirmation in the editor for consequential tools. The server offers the 16 tools of Ninerr's catalog (packages/mcp-protocol/src/tools.mjs); any other name is denied as unknown.",
    dependsOn: ["agent-runtime", "document-model", "history", "collaboration", "studio-host"],
  },
  {
    id: "design-assurance",
    title: "Design assurance",
    owner: "@ninerr/design-assurance",
    status: "implemented",
    boundary: "Deterministic local design checks with rule packs, including an accessibility audit of generated and imported output; findings outrank probabilistic recommendations. Browser-scan targets are classified by network-policy.",
    dependsOn: ["document-model", "network-policy"],
  },
  {
    id: "decision-router",
    title: "Decision router",
    owner: "@ninerr/decision-router",
    status: "implemented",
    boundary: "Provider-neutral decisions with confidence, abstention, and review routing; never overrides deterministic violations.",
    dependsOn: ["design-assurance"],
  },
  {
    id: "decision-assurance",
    title: "Decision assurance",
    owner: "@ninerr/decision-assurance",
    status: "stub",
    boundary: "Assures sets of agent-generated alternatives: deterministic rule-pack, accessibility, layout, and design-system (type scale, spacing grid) checks decide eligibility first; optional decision-router ranking orders eligible candidates; explicit abstention with preserved rationale and evidence. Color-contrast and token-conformance checks are planned until snapshots carry color and token data. Records and recommends only; never mutates documents or applies candidates.",
    dependsOn: ["decision-router", "design-method"],
  },
  {
    id: "delivery-governance",
    title: "Delivery governance",
    owner: "@ninerr/delivery-governance",
    status: "implemented",
    boundary: "Exact-head qualification records, invalidation on mutation, repair ancestry, and ask-user gates for source delivery.",
    dependsOn: ["agent-supervisor"],
  },
  {
    id: "design-method",
    title: "Design method and resources",
    owner: "@ninerr/design-method",
    status: "implemented",
    boundary: "Explainable method rule packs, deterministic review candidates, checklists, and the licensed resource registry.",
    dependsOn: ["design-assurance"],
  },
  {
    id: "agent-workspace",
    title: "Multi-agent workspace",
    owner: "@ninerr/agent-workspace",
    status: "implemented",
    boundary: "Program role registry with capability scopes, role assignment, out-of-scope rejection, and an append-only attributed action ledger with cancellation and reversal marking. Records and gates agent work only; never mutates documents, executes tools, or reverses history.",
    dependsOn: ["agent-runtime", "agent-events", "agent-supervisor", "collaboration"],
  },
  {
    id: "visual-git",
    title: "Visual Git",
    owner: "@ninerr/visual-git",
    status: "implemented",
    boundary: "Design snapshots bound to source commits, structural diffs, anchored review comments, design/code links, three-way conflict reports, and exact-head acceptance gates. Records, compares, and gates only; never executes git, mutates documents, or produces merged snapshots.",
    dependsOn: ["document-model", "code-ir"],
  },
  {
    id: "architecture-ownership",
    title: "Architecture ownership map",
    owner: "@ninerr/architecture",
    status: "implemented",
    boundary: "Machine-checked subsystem ownership catalog and its validation. Declarative only; owns no runtime behavior.",
    dependsOn: [],
  },
  {
    id: "network-policy",
    title: "Network capability policy and providers",
    owner: "@ninerr/network-policy",
    status: "implemented",
    boundary: "Default-deny network capability policy (offline, local-only, allowlist grants) with two-phase URL and resolved-address decisions, the single owner of address classification (consumed by import-stack, intake, and design-assurance browser scans), a bring-your-own provider registry holding credential references only, and offline readiness reporting. Decides only; never opens connections, resolves names, or stores credential values.",
    dependsOn: [],
  },
  {
    id: "intake",
    title: "Website and app intake product layer",
    owner: "@ninerr/intake",
    status: "implemented",
    boundary: "Review-before-commit summaries of import proposals, web semantics derived only from markup (OBSERVED evidence), commit of reviewed imports into persisted projects through the import-stack history transaction, network imports gated by import.fetch policy decisions, and an advisory accessibility summary of each proposal from design-assurance. Composes import-stack, network-policy, persistence, and design-assurance; creates no second document authority.",
    dependsOn: ["import-export", "network-policy", "persistence", "history", "design-assurance"],
  },
  {
    id: "studio-host",
    title: "Studio host",
    owner: "@ninerr/studio-host",
    status: "implemented",
    boundary: "Single writer of an open project for the product surfaces: a loopback-only HTTP API (127.0.0.1, per-launch token, Host and Origin checks) over persistence, history and collaboration attribution, with undo/redo as committed inverse transactions, a server-sent change stream, and lock and recovery reporting (PC1); it serves the editor (PC4) and hosts the MCP endpoint and agent registry (PC5), and imports reviewed HTML offline through import-stack and intake (PC6). It links one local code folder per project and brings components in from it, writing reviewed edits back to their files (`/api/codebase/*`, person-only, PC11a). Local web mode (`npm start`, scripts/ninerr.mjs, PC7) runs it directly, and the desktop app runs it in Electron's main process (PC9).",
    dependsOn: ["persistence", "history", "collaboration", "network-policy", "import-export", "intake"],
  },
  {
    id: "editor-shell",
    title: "Editor application shell",
    owner: "@ninerr/studio-web",
    status: "implemented",
    boundary: "The browser editor the studio host serves: project open and create, layers tree, inspector, live history with attribution, undo/redo, lock takeover and recovery dialogs, and keyboard operation, over the canvas (PC4); the import and Code dialogs, including the Codebase section that connects a folder, brings components in and writes previewed edits back (PC6, PC11b). Every edit is a history transaction committed by the host; the editor's document copy advances only by the host's change events.",
    dependsOn: ["studio-host", "canvas-viewport", "selection-transform", "history"],
  },
  {
    id: "desktop-bridge",
    title: "Desktop bridge",
    owner: "@ninerr/desktop",
    status: "stub",
    boundary: "The desktop app: a thin Electron shell that runs the studio host in its main process and shows the editor in one context-isolated, sandboxed window with no Node and a minimal preload, denied navigation, windows, webviews, downloads, permissions and every request but the host's (PC9a). Packages for Linux x64, macOS arm64 and Windows x64 are a Ninerr-owned assembly of the pinned, SHA-256-verified Electron runtime with its fuses set (no RunAsNode, NODE_OPTIONS or inspector), smoke-tested and journey-tested per platform (PC9b, PC10). Publisher signing and notarization are planned (#139).",
    dependsOn: ["studio-host", "mcp-surface", "persistence"],
  },
  {
    id: "sandbox-security",
    title: "Sandbox and security",
    owner: "@ninerr/import-stack",
    status: "stub",
    boundary: "Import sanitization, authority limits, and bounded capture are implemented. General execution sandboxing is planned.",
    dependsOn: ["document-model", "agent-supervisor"],
  },
  {
    id: "plugin-surface",
    title: "Plugin surface",
    owner: "@ninerr/plugins",
    status: "planned",
    boundary: "Capability-scoped plugin and connector surface for optional providers. No implicit authority.",
    dependsOn: ["mcp-surface", "sandbox-security"],
  },
] as const;

export const NINERR_ARCHITECTURE_MAP: ArchitectureMap = normalizeArchitectureMap({
  schemaVersion: 1,
  subsystems: [...SUBSYSTEMS],
});
